#!/bin/bash

# TestOps Copilot — Demo Setup
# Single command to set up the demo environment from a clean clone.
# Modeled after emhub's deploy-dev.sh pattern: sequential, fail-fast, clear output.
#
# Usage: npm run deploy:demo
#   OR:  bash scripts/deploy-demo.sh

set -e  # Exit on any error

# ── Colors ──────────────────────────────────────────────────────────────
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo -e "${BLUE}==================================${NC}"
echo -e "${BLUE}TestOps Copilot — Demo Setup${NC}"
echo -e "${BLUE}==================================${NC}"
echo ""

# ── Step 1: Check requirements ──────────────────────────────────────────
echo -e "${YELLOW}Step 1: Checking requirements...${NC}"

command -v node >/dev/null 2>&1 || {
    echo -e "${RED}Error: Node.js is required but not installed.${NC}"
    exit 1
}
command -v npm >/dev/null 2>&1 || {
    echo -e "${RED}Error: npm is required but not installed.${NC}"
    exit 1
}

NODE_MAJOR=$(node -v | sed 's/v//' | cut -d. -f1)
if [ "$NODE_MAJOR" -lt 18 ]; then
    echo -e "${RED}Error: Node.js 18+ required (found $(node -v))${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Node.js $(node -v), npm v$(npm -v)${NC}"
echo ""

# ── Step 2: Install dependencies ────────────────────────────────────────
echo -e "${YELLOW}Step 2: Installing dependencies...${NC}"

NEEDS_INSTALL=false
[ ! -d "node_modules" ] && NEEDS_INSTALL=true
[ ! -d "backend/node_modules" ] && NEEDS_INSTALL=true
[ ! -d "frontend/node_modules" ] && NEEDS_INSTALL=true

if [ "$NEEDS_INSTALL" = true ]; then
    npm install
else
    echo "  Dependencies already installed (skipping)"
fi

echo -e "${GREEN}✓ Dependencies ready${NC}"
echo ""

# ── Step 3: Set up environment files ────────────────────────────────────
echo -e "${YELLOW}Step 3: Setting up environment...${NC}"

# Backend .env — create minimal demo config if missing
if [ ! -f "backend/.env" ]; then
    JWT_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
    JWT_REFRESH=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
    SESSION_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
    CSRF_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
    cat > backend/.env << EOF
# Auto-generated by deploy-demo.sh
NODE_ENV=development
PORT=4000
DATABASE_URL="file:./prisma/dev.db"
JWT_SECRET=${JWT_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH}
JWT_EXPIRES_IN=24h
JWT_REFRESH_EXPIRES_IN=7d
SESSION_SECRET=${SESSION_SECRET}
CSRF_SECRET=${CSRF_SECRET}
AI_ENABLED=true
AI_PROVIDER=mock
AI_MODEL=mock
AI_FEATURE_RCA_MATCHING=false
GIPHY_ENABLED=true
REDIS_ENABLED=false
CORS_ORIGIN=http://localhost:5173
EOF
    echo -e "  Created backend/.env (demo config)"
else
    echo -e "  Using existing backend/.env"
    # Ensure PORT is 4000 (matches Vite proxy target)
    if grep -q 'PORT=3000' backend/.env 2>/dev/null; then
        sed -i.bak 's|PORT=3000|PORT=4000|' backend/.env
        rm -f backend/.env.bak
        echo -e "  ${YELLOW}→ Patched PORT to 4000${NC}"
    fi
    # Ensure DATABASE_URL points to the correct SQLite path for demo mode
    if ! grep -q 'DATABASE_URL.*file:./prisma/dev.db' backend/.env 2>/dev/null; then
        sed -i.bak 's|DATABASE_URL=.*|DATABASE_URL="file:./prisma/dev.db"|' backend/.env
        rm -f backend/.env.bak
        echo -e "  ${YELLOW}→ Patched DATABASE_URL to file:./prisma/dev.db${NC}"
    fi
    # Ensure Redis is disabled for demo mode
    if ! grep -q 'REDIS_ENABLED' backend/.env 2>/dev/null; then
        echo 'REDIS_ENABLED=false' >> backend/.env
        echo -e "  ${YELLOW}→ Added REDIS_ENABLED=false${NC}"
    fi
    # Disable Weaviate/RCA matching in demo mode (no vector DB available)
    if ! grep -q 'AI_FEATURE_RCA_MATCHING' backend/.env 2>/dev/null; then
        echo 'AI_FEATURE_RCA_MATCHING=false' >> backend/.env
        echo -e "  ${YELLOW}→ Added AI_FEATURE_RCA_MATCHING=false${NC}"
    fi
fi

# Frontend .env — create if missing
if [ ! -f "frontend/.env" ]; then
    cat > frontend/.env << EOF
# Auto-generated by deploy-demo.sh
VITE_API_URL=http://localhost:4000
VITE_WEBSOCKET_URL=ws://localhost:4000
EOF
    echo -e "  Created frontend/.env"
else
    echo -e "  Using existing frontend/.env"
fi

echo -e "${GREEN}✓ Environment configured${NC}"
echo ""

# ── Step 4: Generate Prisma client (SQLite schema) ──────────────────────
echo -e "${YELLOW}Step 4: Generating Prisma client (SQLite)...${NC}"

cd backend
rm -rf node_modules/.prisma
cp prisma/schema.dev.prisma prisma/schema.prisma
npx prisma generate --schema=prisma/schema.dev.prisma 2>&1 | grep -E "✔|Generated" || true

echo -e "${GREEN}✓ Prisma Client generated${NC}"
echo ""

# ── Step 5: Create demo database ────────────────────────────────────────
echo -e "${YELLOW}Step 5: Creating demo database...${NC}"

rm -f prisma/dev.db prisma/dev.db-journal
npx prisma db push --schema=prisma/schema.dev.prisma --accept-data-loss --force-reset 2>&1 | grep -E "🚀|created|sync" || true

echo -e "${GREEN}✓ SQLite database created${NC}"
echo ""

# ── Step 6: Seed demo data ──────────────────────────────────────────────
echo -e "${YELLOW}Step 6: Seeding demo data...${NC}"

npx tsx prisma/seed.dev.ts

echo -e "${GREEN}✓ Database seeded${NC}"
echo ""

cd ..

# ── Step 7: Verify ──────────────────────────────────────────────────────
if [ -f "backend/prisma/dev.db" ]; then
    SIZE=$(du -h "backend/prisma/dev.db" | cut -f1)
    echo -e "${GREEN}==================================${NC}"
    echo -e "${GREEN}✓ Demo environment ready!${NC}"
    echo -e "${GREEN}==================================${NC}"
    echo ""
    echo -e "  Database: backend/prisma/dev.db (${SIZE})"
    echo ""
    echo -e "${BLUE}Test accounts${NC} (all use password: ${GREEN}demo123${NC}):"
    echo -e "  admin@testops.ai     — Site Admin (full access)"
    echo -e "  lead@testops.ai      — QA Lead (team owner, pipeline config)"
    echo -e "  engineer@testops.ai  — QA Engineer (run tests, view results)"
    echo -e "  viewer@testops.ai    — Stakeholder (read-only dashboards)"
    echo ""
    echo -e "${BLUE}To start:${NC}   npm run dev"
    echo -e "  Frontend:  http://localhost:5173"
    echo -e "  Backend:   http://localhost:4000"
    echo ""
else
    echo -e "${RED}Error: Database file was not created${NC}"
    exit 1
fi

exit 0
